# Generated by Django 6.0.3 on 2026-04-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='is_aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dados_faciais',
            field=models.TextField(),
        ),
    ]
