# Generated by Django 6.0.3 on 2026-05-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_is_aprovado_alter_aluno_dados_faciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto_perfil',
            field=models.ImageField(default=1, upload_to='perfil_alunos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dados_faciais',
            field=models.TextField(blank=True, null=True),
        ),
    ]
