# Generated by Django 6.0.3 on 2026-04-22 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_aluno_is_aprovado_alter_aluno_dados_faciais'),
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('embarque', 'Embarque'), ('desembarque', 'Desembarque'), ('desconhecido', 'Face Desconhecida')], max_length=20)),
                ('foto_capturada', models.ImageField(blank=True, null=True, upload_to='capturas_camera/')),
                ('autorizado', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='alunos.aluno')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='transporte.rota')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
