# Generated by Django 6.0.3 on 2026-04-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name_plural': 'Instituições'},
        ),
        migrations.AlterModelOptions(
            name='responsavel',
            options={'verbose_name_plural': 'Responsáveis'},
        ),
    ]
