# Generated by Django 6.0.3 on 2026-05-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_first_name_alter_usuario_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='foto',
            field=models.ImageField(upload_to='fotos_responsaveis/'),
        ),
    ]
