# Generated by Django 6.0.3 on 2026-05-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_responsavel_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorista',
            old_name='foto',
            new_name='foto_perfil',
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='foto',
            new_name='foto_perfil',
        ),
    ]
