# Generated by Django 6.0.3 on 2026-05-12 19:15

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_foto_motorista_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='foto_perfil',
            field=models.ImageField(upload_to='fotos_motoristas/'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='foto_perfil',
            field=models.ImageField(upload_to=usuarios.models.renomear_foto_responsavel),
        ),
    ]
