# Generated by Django 6.0.3 on 2026-04-22 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_aluno_is_aprovado_alter_aluno_dados_faciais'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=False)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenadas', to='transporte.rota')),
            ],
            options={
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField()),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('cor', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_veiculos/')),
                ('alunos_autorizados', models.ManyToManyField(blank=True, related_name='veiculos', to='alunos.aluno')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.instituicao')),
                ('motoristas_autorizados', models.ManyToManyField(blank=True, related_name='veiculos', to='usuarios.motorista')),
            ],
        ),
        migrations.AddField(
            model_name='rota',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.veiculo'),
        ),
    ]
