# Generated by Django 6.0.3 on 2026-04-22 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
        ('usuarios', '0002_alter_instituicao_options_alter_responsavel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.motorista'),
        ),
        migrations.AlterField(
            model_name='rota',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.veiculo'),
        ),
    ]
