# Generated by Django 6.0.3 on 2026-05-13 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_alter_rota_motorista_alter_rota_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='instituicao',
        ),
    ]
